version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pessoal

  django:
    image: site-pessoal
    restart: always
    command: gunicorn site_pessal.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose:
      - 8000
    depends_on:
       - db

  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static:
  media: