# Generated by Django 2.2.1 on 2019-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('file', models.FileField(upload_to='papers')),
                ('booktitle', models.TextField()),
                ('Year', models.TextField()),
            ],
        ),
    ]
